config/routes.rb
Rails.application.routes.draw do
  resources :chapters
  resources :evaluations
  devise_for :users
  authenticated :user do
    root "pages#index", as: :authenticated_root
  end
  unauthenticated :user do
    root "pages#landing_page"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: %i[ show edit update destroy ]

  # GET /chapters or /chapters.json
  def index
    @chapters = Section.all
  end

  # GET /chapters/1 or /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Section.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters or /chapters.json
  def create
    @chapter = Section.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to chapter_url(@chapter), notice: "Chapter was successfully created." }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1 or /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to chapter_url(@chapter), notice: "Chapter was successfully updated." }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1 or /chapters/1.json
  def destroy
    @chapter.destroy

    respond_to do |format|
      format.html { redirect_to chapters_url, notice: "Chapter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chapter_params
      params.require(:chapter).permit(:name, :description, :type, :body, :user_id)
    end
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: %i[ show edit update destroy ]

  # GET /evaluations or /evaluations.json
  def index
    @evaluations = Section.all
  end

  # GET /evaluations/1 or /evaluations/1.json
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = Section.new
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations or /evaluations.json
  def create
    @evaluation = Section.new(evaluation_params)

    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to evaluation_url(@evaluation), notice: "Evaluation was successfully created." }
        format.json { render :show, status: :created, location: @evaluation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1 or /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to evaluation_url(@evaluation), notice: "Evaluation was successfully updated." }
        format.json { render :show, status: :ok, location: @evaluation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1 or /evaluations/1.json
  def destroy
    @evaluation.destroy

    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: "Evaluation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def evaluation_params
      params.require(:evaluation).permit(:name, :description, :type, :body, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def landing_page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chapters/_chapter.html.erb
<div id="<%= dom_id chapter %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= chapter.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= chapter.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Type:</strong>
    <%= chapter.type %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= chapter.body %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= chapter.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this chapter", chapter, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this chapter", edit_chapter_path(chapter), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/chapters/_form.html.erb
<%= form_with(model: chapter, class: "contents") do |form| %>
  <% if chapter.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
        <% chapter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :type %>
    <%= form.text_field :type, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing chapter</h1>

  <%= render "form", chapter: @chapter %>

  <%= link_to "Show this chapter", @chapter, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to chapters", chapters_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/chapters/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Chapters</h1>
    <%= link_to "New chapter", new_chapter_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="chapters" class="min-w-full">
    <%= render @chapters %>
  </div>
</div>

app/views/chapters/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New chapter</h1>

  <%= render "form", chapter: @chapter %>

  <%= link_to "Back to chapters", chapters_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/chapters/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @chapter %>

    <%= link_to "Edit this chapter", edit_chapter_path(@chapter), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this chapter", chapter_path(@chapter), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to chapters", chapters_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/evaluations/_evaluation.html.erb
<div id="<%= dom_id evaluation %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= evaluation.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= evaluation.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Type:</strong>
    <%= evaluation.type %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= evaluation.body %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= evaluation.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this evaluation", evaluation, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this evaluation", edit_evaluation_path(evaluation), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/evaluations/_form.html.erb
<%= form_with(model: evaluation, class: "contents") do |form| %>
  <% if evaluation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(evaluation.errors.count, "error") %> prohibited this evaluation from being saved:</h2>

      <ul>
        <% evaluation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :type %>
    <%= form.text_field :type, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/evaluations/_welcome.html.erb
<section class="flex justify-around items-center h-screen">
    <div>
        <%= image_tag("6099984.jpg", width: "400") %>
    </div>
    <div>
        <h1 class="text-center text-3xl font-bold text-evaluationStrong">Evaluations</h1>
        <p class="text-center py-2 font-semibold text-evaluationStrong">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit <br>
            Neque, itaque cupiditate omnis tempora aliquid doloribus corrupti <br> 
            provident ducimus blanditiis fugiat totam quis sequi quaerat. Vero error fugit <br> nisi laboriosam culpa!
        </p>
        <div class="flex justify-center my-4">
            <%= button_to root_path, id: "create_evaluation_welcome" do %>
                <div class="p-3 bg-evaluationStrong text-white text-sm font-semibold rounded-lg">
                    Create evaluation
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/evaluations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing evaluation</h1>

  <%= render "form", evaluation: @evaluation %>

  <%= link_to "Show this evaluation", @evaluation, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to evaluations", evaluations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/evaluations/index.html.erb
<%= render 'welcome' %>

app/views/evaluations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New evaluation</h1>

  <%= render "form", evaluation: @evaluation %>

  <%= link_to "Back to evaluations", evaluations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/evaluations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @evaluation %>

    <%= link_to "Edit this evaluation", edit_evaluation_path(@evaluation), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this evaluation", evaluation_path(@evaluation), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to evaluations", evaluations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://cdn.tailwindcss.com"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/main_navbar" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <main class="flex justify-between">
      <div class="w-full">
        <%= yield %>
      </div>
      <nav class="bg-footerGray p-2">
        <%= render "shared/right_navbar" %>
      </nav>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/index.html.erb
<section class="flex justify-around h-screen items-center">
  <div>
    <h1 class="text-center font-bold text-mainColor text-3xl">Survey Rails App</h1>
    <p class="text-center text-sm text-mainColor font-semibold">suervey-rails-app.com</p>
    <p class="py-5 text-sm font-semibold text-mainColor text-center">
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptates cumque,<br>
       quidem doloribus laborum, ipsam nemo enim provident excepturi non deleniti<br>
        quia beatae unde. Ex corrupti earum autem! Explicabo, dolor aliquam <br>
    </p>
    <div class="flex w-full justify-around">
      <div class="bg-evaluationStrong p-3 text-white text-sm font-semibold rounded-lg">
        <%= button_to evaluations_path, method: :get, id: "create_evaluation_index" do %>
          Create evaluation.
        <% end %>
      </div>
      <div class="bg-chapterStrong p-3 text-white text-sm font-semibold rounded-lg">
        <%= button_to chapters_path, method: :get, id: "create_evaluation_index" do %>
          Create chapter.
        <% end %>
      </div>
    </div>
  </div>
  <div class="flex flex-col justify-center">
    <span class="text-center text-lg font-semibold text-mainColor">¡You are in!</span>
    <%= image_tag("3254897.jpg", width: "400") %>
  </div>
</section>

app/views/pages/landing_page.html.erb
<main>
  <section class="h-96 flex justify-around items-center gap-10 bg-mainColor">
    <div class="text-white text-center">
      <p class="font-semibold text-3xl py-5">
        Survey Rails App.
      </p>
      <p>
        Create your first survey.
      </p>
      <p>
        Start sending surveys to different companies around the world.
      </p>
      <div class="py-5 text-black">
        <%= button_to root_path, id: 'get_started' do %>
          <div class="bg-signIn p-4 rounded-lg">
            <i class="fa-solid fa-circle-arrow-right"></i> 
            <span class="ml-1">Get Started</span>
          </div>
        <% end %>
      </div>
      <p class="text-sm font-semibold">
        survey-rails-app.com
      </p>
    </div>
    <div>
      <%= image_tag("ruby.png", width: "300") %>
    </div>
  </section>
  <section>
    <div class="flex justify-around p-10">
      <%= image_tag("Amazon.png", width: "150") %>
      <%= image_tag("Facebook.png", width: "150") %>
      <%= image_tag("Google.png", width: "150") %>
      <%= image_tag("Instagram.png", width: "150") %>
      <%= image_tag("LinkedIn.png", width: "150") %>
      <%= image_tag("Spotify.png", width: "150") %>
      <%= image_tag("Twitter.png", width: "150") %>
    </div>
    <p class="text-center text-sm font-semibold text-mainColor p-10">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, ab nulla. Corporis eligendi ratione laboriosam et. Suscipit, quos magnam ut impedit ullam sequi distinctio deserunt quae ipsum explicabo facilis dolores.
    </p>
  </section>
  <div class="text-center text-sm text-semibold border-2">
    ---
  </div>
  <section class="h-96 flex justify-around items-center">
    <div>
      <%= image_tag("2126918.jpg", width: "350") %>
    </div>
    <div>
      <h2 class="font-semibold text-center text-mainColor text-2xl pd-5">¡Working with your team!</h2>
      <p class="text-sm text-center text-mainColor font-semibold">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, ab nulla. Corporis eligendi ratione laboriosam et. <br>
        Suscipit, quos magnam ut impedit ullam sequi distinctio deserunt quae ipsum explicabo facilis dolores. Lorem ipsum dolor <br>
        sit amet consectetur adipisicing elit. <br>
        Nostrum tempora sed numquam libero maxime illo assumenda impedit magni aut? Quas impedit adipisci nulla ea at commodi sequi officiis id nesciunt. <br>
    </div>
  </section>
  <div class="text-center text-sm text-semibold border-2">
    ---
  </div>
  <section class="h-96 flex justify-around items-center">
    <div>
      <h2 class="font-semibold text-center text-mainColor text-2xl pd-5">Answer the survey.</h2>
      <p class="text-sm text-center text-mainColor font-semibold">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, ab nulla. Corporis eligendi ratione laboriosam et. <br>
        Suscipit, quos magnam ut impedit ullam sequi distinctio deserunt quae ipsum explicabo facilis dolores. Lorem ipsum dolor <br>
        sit amet consectetur adipisicing elit. <br>
        Nostrum tempora sed numquam libero maxime illo assumenda impedit magni aut? Quas impedit adipisci nulla ea at commodi sequi officiis id nesciunt. <br>
    </div>
    <div>
      <%= image_tag("4048544.jpg", width: "350") %>
    </div>
  </section>
    <div class="text-center text-sm text-semibold border-2">
      ---
    </div>
  <section class="h-96 flex flex-col justify-around items-center m-32">
    <div>
      <h2 class="font-semibold text-center text-mainColor text-2xl pd-5">Answer the survey.</h2>
    </div>
    <div class="flex py-10 w-3/6 justify-between">
      <%= image_tag("2978479.jpg", width: "320") %>
      <%= image_tag("check_box_image.png", width: "250") %>
    </div>
    <div>
      <p class="text-sm text-center text-mainColor font-semibold">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, ab nulla. Corporis eligendi ratione laboriosam et. Suscipit, quos magnam ut impedit ullam sequi distinctio deserunt quae ipsum explicabo facilis dolores.
    </div>
  </section>
</section>
<div class="text-center text-sm text-semibold border-2">
  ---
</div>
<section class="h-96 flex flex-col justify-around items-center m-32">
  <div>
    <h2 class="font-semibold text-center text-mainColor text-2xl pd-5">Answer the survey.</h2>
  </div>
  <div class="flex py-10">
    <%= image_tag("posting_image.png") %>
  </div>
  <div>
    <p class="text-sm text-center text-mainColor font-semibold">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, ab nulla. Corporis eligendi ratione laboriosam et. Suscipit, quos magnam ut impedit ullam sequi distinctio deserunt quae ipsum explicabo facilis dolores.
  </div>
</section>

</main>

app/views/shared/_footer.html.erb
<footer>
    <ul class="flex justify-center gap-10 p-3 bg-footerGray text-sm font-semibold">
        <li>Privacy Policy</li>
        <li>About</li>
        <li>Home</li>
        <li>Sign In</li>
        <li>Sign Up</li>
    </ul>
    <p class="text-center p-4 bg-mainColor text-white">
        Survey Rails App @ 2024 | Jason Cacante
    </p>
</footer>

app/views/shared/_main_navbar.html.erb
<header>
    <nav class="flex justify-between bg-mainColor text-white p-4">
        <ul>
            <%= link_to root_path, class: "flex gap-3" do %>
                <i class="fa-solid fa-book text-2xl"></i> Suvery Rails App.
            <% end %>
        </ul>
        <ul class="flex gap-3">
            <% if current_user %>
              <li>
                  <%= current_user.email %>
              </li>
              <li class="bg-red-700 rounded">
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "py-1 px-4 text-sm text-black font-semibold" %>
              </li>
              <li class="flex items-center">
                <%= button_to root_path, id: "open_options_icon" do %>
                    <i class="fa-solid fa-gear"></i>
                <% end %>
              </li>
            <% else %>
              <li class="bg-signIn rounded">
                  <%= button_to "Sign in", new_user_session_path, method: :get, class: "py-1 px-4 text-sm text-black font-semibold" %>
              </li>
              <li class="bg-signUp rounded">
                  <%= button_to "Sign up", new_user_registration_path, method: :get, class: "py-1 px-4 text-sm text-black font-semibold" %>
              </li>
            <% end %>
        </ul>
    </nav>
</header>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag 'modal' do %>
<% end %>

app/views/shared/_right_navbar.html.erb
<ul class="flex flex-col justify-center">
    <li class="flex justify-center py-2">
        <%= link_to root_path, id: 'home_icon' do %>
            <i class="fa-solid fa-house"></i>
        <% end %>
    </li>
    <li class="flex justify-center py-2">
        <%= link_to root_path, id: 'evaluations_icon' do %>
            <i class="fa-solid fa-square-ppoll-horizontal"></i>
        <% end %>
    </li>
    <li class="flex justify-center py-2">
        <%= link_to root_path, id: 'chapters_icon' do %>
            <i class="fa-solid fa-list-check"></i>
        <% end %>
    </li>
    <li class="flex justify-center py-2">
        <%= link_to root_path, id: 'surveys_icon' do %>
            <i class="fa-solid fa-folder-open"></i>
        <% end %>
    </li>
</ul>